name: Build and deploy to docs
permissions:
  id-token: write   # required for GitHub OIDC
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools

      - name: Restore and pack
        run: |
          cd src
          cd BBH
          dotnet restore BBH.slnx
          dotnet tool restore
          dotnet r pack

      # - name: NuGet Login
      #   uses: NuGet/login@v1
      #   id: login
      #   with:
      #     user: ignatandrei

      # - name: Upload NuGet artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: nuget-packages
      #     path: src/nu/*
      #     retention-days: 1
          
      - name: Push package
        run: |
          dotnet nuget push src/nu/* --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://www.nuget.org/api/v2/package


      - name: Publish Blazor app
        run: |
          git pull
          rm -rf docs || true
          cd src/BBH
          dotnet tool restore
          dotnet r publishDocs
          

      - name: Copy published files to docs
        run: |
          mkdir docs

          cp -r src/BBH/Release/UIBlazor/wwwroot/* docs/
          cd docs
          touch .nojekyll

      - name: Commit and push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A docs
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "CI: publish Blazor site to /docs"
            git push origin HEAD:main
          fi
   